// src/pages/Login/Login.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './Login.css';
import logoIssi from '../../assets/logo/logo-issi.svg';
import logoOperacional from '../../assets/logo/logo-operacional.svg';
import logoTi from '../../assets/logo/logo-ti.svg';
import { FaEye, FaEyeSlash } from 'react-icons/fa';
import { login } from '../../services/auth';
import { useUser } from '../../context/userContext';

const Login = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const navigate = useNavigate();

  if (useUser().isLoggedIn()) {
    navigate('/dashboard');
  }

  const handleLogin = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    setShowPassword(false);

    if (!username) {
      setError({ userName: 'Usuário é obrigatório' });
      return;
    }

    if (!password) {
      setError({ password: 'Senha é obrigatória' });
      return;
    }

    try {
      const data = await login(username.trim(), password);
      console.log(data);
      navigate('/dashboard');
    } catch (error) {
      console.error('Erro de login:', error.message);
      setError({ userName: 'Usuário ou senha inválidos' });
      setIsLoading(false);
    }
  };

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  return (
    <div className="login-container">
      <div className="login-background">
        <div className="photo-credit">Foto: Acervo Insanos M.C.</div>
      </div>
      <div className="login-form-container">
        <div className="login-header">
          <div className="logo-title-container">
            <img src={logoIssi} alt="Logo" className="logo" />
            <div className="title-container">
              <h1>Sistema de Gestão</h1>
              <h2>de Staff</h2>
            </div>
          </div>
          <h2 className="welcome-text">Seja bem vindo!</h2>
        </div>

        <div className="login-form">
          <form onSubmit={handleLogin}>
            <div className="form-group">
              <label htmlFor="username">Usuário</label>
              <input
                type="text"
                id="username"
                placeholder="Digite o usuário"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
              {error?.userName && (
                <div className="error-message">{error.userName}</div>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="password">Senha</label>
              <div className="password-input-container">
                <input
                  type={showPassword ? 'text' : 'password'}
                  id="password"
                  placeholder="Digite a senha"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
                <span
                  className="password-toggle"
                  onClick={togglePasswordVisibility}
                  title={showPassword ? 'Ocultar senha' : 'Mostrar senha'}
                >
                  {showPassword ? <FaEye /> : <FaEyeSlash />}
                </span>
              </div>
              {error?.password && (
                <div className="error-message">{error.password}</div>
              )}
            </div>

            <div className="form-options">
              <div className="remember-me">
                <input type="checkbox" id="remember" />
                <label htmlFor="remember">Lembrar-me</label>
              </div>
              <a href="#" className="forgot-password">
                Esqueci a senha
              </a>
            </div>

            <button type="submit" className="login-button" disabled={isLoading}>
              Acessar
              {isLoading && <span className="loading-spinner"></span>}
            </button>
          </form>

          <div className="support-contact">
            <button className="support-button">Contato com o suporte</button>
          </div>
        </div>

        <div className="login-footer">
          <div className="footer-logos">
            <img src={logoOperacional} alt="Logo Operacional" />
            <img src={logoTi} alt="Logo TI" />
          </div>
          <p>© Insanos M.C. Tecnologia e Instrução 2025</p>
        </div>
      </div>
    </div>
  );
};

export default Login;

// src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { Router } from '@angular/router';
import { LoginCredentials } from '../../../models/user.model';
import { AuthService } from '../../../core/services/auth.service';
import { catchError } from 'rxjs/operators';
import { of } from 'rxjs';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatCardModule,
    MatInputModule,
    MatButtonModule,
    MatFormFieldModule,
    MatIconModule,
    MatCheckboxModule
  ],
  template: `
    <div class="login-container">
      <div class="login-background">
        <div class="photo-credit">Foto: Acervo Insanos M.C.</div>
      </div>
      <div class="login-form-container">
        <div class="login-header">
          <div class="logo-title-container">
            <img src="assets/logo/logo-issi.svg" alt="Logo" class="logo" />
            <div class="title-container">
              <h1>Sistema de Gestão</h1>
              <h2>de Staff</h2>
            </div>
          </div>
          <h2 class="welcome-text">Seja bem vindo!</h2>
        </div>

        <div class="login-form">
          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
              <label for="username">Usuário</label>
              <input
                type="text"
                id="username"
                formControlName="username"
                placeholder="Digite o usuário"
              />
              <div class="error-message" *ngIf="loginForm.get('username')?.errors?.['required'] && loginForm.get('username')?.touched">
                Usuário é obrigatório
              </div>
            </div>

            <div class="form-group">
              <label for="password">Senha</label>
              <div class="password-input-container">
                <input
                  [type]="showPassword ? 'text' : 'password'"
                  id="password"
                  formControlName="password"
                  placeholder="Digite a senha"
                />
                <span
                  class="password-toggle"
                  (click)="togglePasswordVisibility()"
                  [title]="showPassword ? 'Ocultar senha' : 'Mostrar senha'"
                >
                  <mat-icon>{{ showPassword ? 'visibility_off' : 'visibility' }}</mat-icon>
                </span>
              </div>
              <div class="error-message" *ngIf="loginForm.get('password')?.errors?.['required'] && loginForm.get('password')?.touched">
                Senha é obrigatória
              </div>
            </div>

            <div class="form-options">
              <div class="remember-me">
                <mat-checkbox formControlName="remember">Lembrar-me</mat-checkbox>
              </div>
              <a href="#" class="forgot-password">Esqueci a senha</a>
            </div>

            <button type="submit" class="login-button" [disabled]="loginForm.invalid || isLoading">
              Acessar
              <span class="loading-spinner" *ngIf="isLoading"></span>
            </button>
            <div class="error-message" *ngIf="loginError">{{loginError}}</div>
          </form>

          <div class="support-contact">
            <button class="support-button">Contato com o suporte</button>
          </div>
        </div>

        <div class="login-footer">
          <div class="footer-logos">
            <img src="assets/logo/logo-operacional.svg" alt="Logo Operacional" />
            <img src="assets/logo/logo-ti.svg" alt="Logo TI" />
          </div>
          <p>© Insanos M.C. Tecnologia e Instrução 2025</p>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  loginForm: FormGroup;
  showPassword = false;
  isLoading = false;
  loginError: string | null = null;

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private authService: AuthService
  ) {
    this.loginForm = this.fb.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]],
      remember: [false]
    });
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      this.isLoading = true;
      this.loginError = null;
      const credentials: any = {
        username: this.loginForm.value.username,
        password: this.loginForm.value.password
      };
      this.authService.login(credentials).pipe(
        catchError((err) => {
          this.loginError = 'Usuário ou senha inválidos';
          this.isLoading = false;
          return of(null);
        })
      ).subscribe((res) => {
        this.isLoading = false;
        if (res && res.token) {
          localStorage.setItem('token', res.token);
          if (res.user) {
            localStorage.setItem('user', JSON.stringify(res.user));
          }
          this.router.navigate(['/volunteers']);
        } else if (!this.loginError) {
          this.loginError = 'Usuário ou senha inválidos';
        }
      });
    }
  }
}

<div class="login-container">
  <div class="left-panel">
  </div>
  <div class="right-panel">
    <mat-card class="login-card">
      <mat-card-content>
        <div class="login-header">
          <div class="logo-title-container">
            <img src="assets/logo/logo-issi.svg" alt="Logo" class="logo" />
            <div class="title-container">
              <h1>Sistema de Gestão</h1>
              <h2>de Staff</h2>
            </div>
          </div>
          <h2 class="welcome-text">Seja bem vindo!</h2>
        </div>

        <div class="login-form">
          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Usuário</mat-label>
              <input matInput type="text" formControlName="username" placeholder="Digite o usuário">
              <mat-error *ngIf="loginForm.get('username')?.errors?.['required'] && loginForm.get('username')?.touched">
                Usuário é obrigatório
              </mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Senha</mat-label>
              <input matInput [type]="showPassword ? 'text' : 'password'" formControlName="password" placeholder="Digite a senha">
              <button mat-icon-button matSuffix (click)="togglePasswordVisibility()">
                <mat-icon>{{ showPassword ? 'visibility_off' : 'visibility' }}</mat-icon>
              </button>
              <mat-error *ngIf="loginForm.get('password')?.errors?.['required'] && loginForm.get('password')?.touched">
                Senha é obrigatória
              </mat-error>
            </mat-form-field>

            <div class="form-options">
              <mat-checkbox formControlName="remember">Lembrar-me</mat-checkbox>
              <a href="#" class="forgot-password">Esqueci a senha</a>
            </div>

            <button mat-raised-button color="primary" type="submit" class="login-button" [disabled]="loginForm.invalid || isLoading">
              Acessar
              <span class="loading-spinner" *ngIf="isLoading"></span>
            </button>
            <div class="error-message" *ngIf="loginError">{{loginError}}</div>
          </form>

          <div class="support-contact">
            <button mat-button class="support-button">Contato com o suporte</button>
          </div>
        </div>

        <div class="login-footer">
          <div class="footer-logos">
            <img src="assets/logo/logo-operacional.svg" alt="Logo Operacional" />
            <img src="assets/logo/logo-ti.svg" alt="Logo TI" />
          </div>
          <p>© Insanos M.C. Tecnologia e Instrução 2025</p>
        </div>
      </mat-card-content>
    </mat-card>
  </div>
</div>
